# --------------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------------
data:
  fragments_dir: "data"     # directory containing train_fragments.npy etc.
  train_fragments: "fragments_run1000/frag_g4_n1000/fragments_g4_n1000_s42/fragments_train.npy"
  train_ids:       "fragments_run1000/frag_g4_n1000/fragments_g4_n1000_s42/ids_train.npy"
  train_positions: "fragments_run1000/frag_g4_n1000/fragments_g4_n1000_s42/positions_train.npy"
  val_fragments:   "fragments_run1000/frag_g4_n1000/fragments_g4_n1000_s42/fragments_val.npy"
  val_ids:         "fragments_run1000/frag_g4_n1000/fragments_g4_n1000_s42/ids_val.npy"
  val_positions:   "fragments_run1000/frag_g4_n1000/fragments_g4_n1000_s42/positions_val.npy"  
  test_fragments:  "fragments_run1000/frag_g4_n1000/fragments_g4_n1000_s42/fragments_test.npy"
  test_ids:        "fragments_run1000/frag_g4_n1000/fragments_g4_n1000_s42/ids_test.npy"
  test_positions:  "fragments_run1000/frag_g4_n1000/fragments_g4_n1000_s42/positions_test.npy"

# ----------------------------------------
# Hyperparameters
# ----------------------------------------
model:
  embed_dim: 128         # dimensionality of the patch embedding
  lr: 0.0005             # learning rate for the Adam optimizer
  temperature: 0.5      # temperature τ for InfoNCE
  jigsaw_loss_weight: 5.0  # weight for the Jigsaw loss (kept high to force convergence on it)

trainer:
  max_epochs: 30        
  gpus: 0               # 0 for CPU
  precision: 32         # 32-bit floating point

datamodule:
  batch_size_images: 32  # number of *images* per batch; each image → 16 patches
  num_workers: 0        # CPU workers for DataLoader

# ----------------------------------------
# Checkpoint & Logging
# ----------------------------------------
checkpoint:
  monitor: "val/total_loss"    
  mode: "min"
  save_top_k: 1
  dirpath: "lightning_logs/contrastive_model"
  filename: "newbest-{epoch:02d}-{val_loss:.4f}"

logger:
  log_dir: "lightning_logs/"

eval:
  use_histogram_fallback: false
